### PR TITLE
remove rdp wrap as it is dead

### PR DESCRIPTION
**Pull request by G2G2G2G**
also fix alphabetical issue

Thank you for taking the time to work on a PR for Awesome-Sysadmin!

To ensure your PR is dealt with swiftly please check the following:

- [ ] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)
- [ ] Software your are submitting is not your own, unless you have a healthy ecosystem with a few contributors (which aren't your sock puppet accounts).
- [ ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ ] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 80 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [ ] Additions are inserted preserving alphabetical order.
- [ ] Additions are not already listed at [awesome-selfhosted](https://github.com/awesome-foss/awesome-sysadmin)
- [ ] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-foss/awesome-sysadmin/issues) or [PRs](https://github.com/awesome-foss/awesome-sysadmin/pulls), including closed ones.
- [ ] Any category you are creating has the minimum requirement of 3 items.
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

--------------

### Why it is awesome

Please replace this with a short paragraph explaning why you think this software is awesome.

### CODE REVIEW

**Comment by G2G2G2G** [comment]
just glancing at stuff there are a lot of non alphabetical order things

**Comment by PrplHaz4** [comment]
Not exactly "awesome" but rdpwrap is still usable and somewhat maintained here: https://github.com/stascorp/rdpwrap/pull/1160

That PR/contributer seems more trustworthy than other forks...

**Comment by G2G2G2G** [comment]
lol we had a discussion in another thread to remove it.
I look through issues all the time before removing these projects.. Why don't they fork it and make the latest issue "new fork of this project" like 90% of other projects do when they move..

**Review by nodiscc — APPROVED** [review]
Thanks

See https://github.com/awesome-foss/awesome-sysadmin/issues/405

**Pull request merged**
