### PR TITLE
Added RuckZuck to Client Management section

### PR DESCRIPTION
**Pull request by danfossi**
Select a software from the repository and RuckZuck handles the download and installation for you. RuckZuck can detect and update existing software that was not installed with RuckZuck.

### CODE REVIEW

**Review by KieranRobson — APPROVED** [review]

**Comment by nodiscc** [comment]
- How is this better than https://chocolatey.org/?
- How is the app repository maintained/curated/kept secure?

**Comment by danfossi** [comment]
Chocolatey does not allow the installation of applications in the standard system path (%PROGRAMFILES%), except for the paid version, but installs the applications within the user profile.

**Review by nodiscc — DISMISSED** [review]

**Comment by Technetium1** [comment]
@danfossi this is wrong. You simply need admin permissions to do so.

**Comment by Technetium1** [comment]
@nodiscc 3361 packages on Chocolatey, but only 615 on RuckZuck. Not sure that this is awesome enough.

**Comment by nodiscc** [comment]
A discussion was started in https://github.com/awesome-foss/awesome-sysadmin/pull/357 to determine what should/should not be added to the list ("quality" guidelines).

Your feedback is welcome.

**Pull request closed without merging**
