### PR TITLE
Add link to LizardFS

### PR DESCRIPTION
**Pull request by jadolg**
### Source URL
https://github.com/lizardfs

### why it is awesome
LizardFS – Software Defined Storage is a distributed, scalable, fault-tolerant, and highly available file system. It allows combining disk space located on several servers into a single namespace visible on Unix-like and Windows systems in the same way as other file systems. LizardFS was inspired by the GoogleFS distributed file system that was introduced in 2010.

### CODE REVIEW

**Review by KieranRobson — APPROVED** [review]

**Review by Technetium1 — APPROVED** [review]
This is a very good addition in my opinion.

**Review by nodiscc — COMMENTED** [review]
- How does it compare/how is it different from other distributed filesystems such as gluster, ceph...?
- Are you aware of large-scale or production deployments?
- It doesn't seem actually very maintained... https://github.com/lizardfs/lizardfs/commits/master, there haven't been significant commits since Nov 2021, 300 issues (but most look triaged/addressed), and a question has been raised at https://github.com/lizardfs/lizardfs/issues/903
- It was removed from Debian Stable due to mutliple reasons (lack of maintenance, depends on EOL Python 2, build failures...) [[1]](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010587) [[2]](https://tracker.debian.org/pkg/lizardfs)

In the current state, I think it should not be added.

**Comment by nodiscc** [comment]
Feedback needed about clarifying quality requirements for awesome-sysadmin: https://github.com/awesome-foss/awesome-sysadmin/pull/357

**Comment by nodiscc** [comment]
I was going to request more information following the new pull request template that was introduced in https://github.com/awesome-foss/awesome-sysadmin/pull/459/files, but after re-reading the discussion above, I think we should not add it (mostly because it relies on an EOL version of Python, it might be OK to keep it running on legacy projects, but recommending it here for new deployments is not). Feel free to open a new PR when it has been ported to Python 3 an new releases are made.

**Pull request closed without merging**
