### PR TITLE
Add Authelia to Identity Management - Single Sign-On (SSO)

### PR DESCRIPTION
**Pull request by knrdl**
Thank you for taking the time to work on a PR for Awesome-Sysadmin!

To ensure your PR is dealt with swiftly please check the following:

- [X] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)
- [X] Software your are submitting is not your own, unless you have a healthy ecosystem with a few contributors (which aren't your sock puppet accounts).
- [X] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [X] Format your submission as follows, where `Demo` and `Clients` are optional.
  Do not add a duplicate `Source code` link if it is the same as the main link.
  Keep the short description under 80 characters and use [sentence case](https://en.wikipedia.org/wiki/Letter_case#Sentence_case)
  for it, even if the project's webpage or readme uses another capitalisation.
  `Demo` links should only be used for interactive demos, i.e. not video demonstrations.
  ``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` ``
- [X] Additions are inserted preserving alphabetical order.
- [X] Additions are not already listed at [awesome-selfhosted](https://github.com/awesome-foss/awesome-sysadmin)
- [X] The `Language` tag is the main **server-side** requirement for the software. Don't include frameworks or specific dialects.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-foss/awesome-sysadmin/issues) or [PRs](https://github.com/awesome-foss/awesome-sysadmin/pulls), including closed ones.
- [X] Any category you are creating has the minimum requirement of 3 items.
- [X] Any software project you are adding to the list is actively maintained.
- [X] The pull request title is informative, unlike "Update README.md".
  Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
  "Remove aaa from bbb" for removing, "Fix license for aaa", etc.

--------------

### Why it is awesome

Please replace this with a short paragraph explaning why you think this software is awesome.

### CODE REVIEW

**Comment by nodiscc** [comment]
Hi @knrdl
You forgot to replace the placeholder (_Please replace this with a short paragraph explaning why you think this software is awesome._). Any way since we're trying to update contribution guidelines/clarify _awesomeness_ criteria (https://github.com/awesome-foss/awesome-sysadmin/pull/357) I will ask you to answer the following questions instead:

- **Have you used it? For how long?**
- **Is this in a personal or professional setup?**
- **How many devices/users/services/... do you manage with it?**
- **Biggest pros/cons compared to other solutions?**
- **Any other comments about your use case, things you've found excellent, limitations you've encountered... ?**

**Comment by knrdl** [comment]
Have you used it? For how long? 
For a couple of month, maybe a year and it works flawless.

Is this in a personal or professional setup?
Only personal. But I would use it professional as well, if there wasn't already a bunch of enterprise crap in place which basically does the same but much more complicated.

How many devices/users/services/... do you manage with it?
A few dozens users/devices. Maybe 30-40 services/webapps handling their auth via authelia.

Biggest pros/cons compared to other solutions?
Pros: super simple, supports SSO, self explaining config file, easy reverse proxy integration, detailed manual
Cons: config changes (e.g. adding a service) require a restart (minimal downtime).

Any other comments about your use case, things you've found excellent, limitations you've encountered... ?
Auth software should run behind the scenes without making trouble or being noticed at all. Authelia works that way for me.

PS: I'm not affiliated with authelia in any way, just a happy user.

**Review by apollo-24 — APPROVED** [review]
SSP

**Review by nodiscc — APPROVED** [review]

**Review by nodiscc — APPROVED** [review]
Thanks for the useful reviews.

**Pull request merged**
